### PR TITLE
Image decryption

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by fidencio** [comment]
As we reached the code / feature freeze for the `v0.2.0` release, let's wait till we cut such a release before merging this one.

**Comment by mythi** [comment]
> As we reached the code / feature freeze for the `v0.2.0` release, let's wait till we cut such a release before merging this one.

This works for me. We now have the updated versions of ocicrypt-rs/image-rs that enable the functionality enclave-cc needs. I could also update this a bit to move to a test image other than something from my repo. :-)

**Comment by fidencio** [comment]
@mythi, `v0.2.0` was tagged this afternoon.  We can go ahead with this one.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @mythi!

**Review by haosanzi — APPROVED** [review]

**Pull request merged**
