### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by dcmiddle**
Enable review notifications on PRs

### CODE REVIEW

**Review by YangLiang3 — COMMENTED** [review]
I and Jia will be CODEOWNER of this project

**Comment by dcmiddle** [comment]
@YangLiang3 yes you are both in the existing github team https://github.com/orgs/confidential-containers/teams/enclave-cc-maintainers/members
The CODEOWNERS file facilitates autonotifications for PRs. 
Sometimes there is a question of permissions. Permissions for each user are not controlled by CODEOWNERS. It only facilitates notifications. Permissions are defined by user or team per repo. In CoCo, convention is to use the github teams. 
It looks like you reopened the PR you previously closed and then merged a different CODEOWNERS file that only lists the 2 of you.

**Comment by dcmiddle** [comment]
rebased

**Review by mythi — APPROVED** [review]

**Review by sameo — APPROVED** [review]

**Comment by sameo** [comment]
@jiazhang0 @YangLiang3 Are you ok with that change? You're definitely part of the code owners team, that does not change.

**Review by jiazhang0 — APPROVED** [review]

**Pull request merged**
