### PR TITLE
Rune initial commit

### PR DESCRIPTION
**Pull request by YangLiang3**
1. add rune initial commit
2. change the path of go module reference
3. remove EPM(enclave pool management) function

### CODE REVIEW

**Comment by jiazhang0** [comment]
Please add the "Fix" line to associate the issue https://github.com/confidential-containers/enclave-cc/issues/5

**Comment by YangLiang3** [comment]
> Please add the "Fix" line to associate the issue #5 @YangLiang3

ok Got it

**Comment by mythi** [comment]
To simplify the installation procedure and maintenance of `enclave-cc` I'd propose we go with `runc`. If `rune` is required at a later point, it might be better to use it from Inclavare containers two avoid the need for having to main two versions of `rune`.

**Comment by YangLiang3** [comment]
> To simplify the installation procedure and maintenance of `enclave-cc` I'd propose we go with `runc`. If `rune` is required at a later point, it might be better to use it from Inclavare containers two avoid the need for having to main two versions of `rune`.
ok, got it. I prefer to use the rune as a default container runtime in enclave-cc. Because of the unchanged's entry point and the same UX.

**Comment by YangLiang3** [comment]
> To simplify the installation procedure and maintenance of `enclave-cc` I'd propose we go with `runc`. If `rune` is required at a later point, it might be better to use it from Inclavare containers two avoid the need for having to main two versions of `rune`.

ok, got it. I prefer to use the rune as a default container runtime in enclave-cc. Because of the unchanged's entry point and the same UX

**Comment by mythi** [comment]
> > To simplify the installation procedure and maintenance of `enclave-cc` I'd propose we go with `runc`. If `rune` is required at a later point, it might be better to use it from Inclavare containers two avoid the need for having to main two versions of `rune`.
> 
> ok, got it. I prefer to use the rune as a default container runtime in enclave-cc. Because of the unchanged's entry point and the same UX

The entry point change is not user visible or the `shim-rune` modification did not work?

**Comment by YangLiang3** [comment]
> 1. add rune initial commit
> 2. change the path of go module reference
> 3. remove EPM(enclave pool management) function

**Comment by YangLiang3** [comment]
> > > To simplify the installation procedure and maintenance of `enclave-cc` I'd propose we go with `runc`. If `rune` is required at a later point, it might be better to use it from Inclavare containers two avoid the need for having to main two versions of `rune`.
> > 
> > 
> > ok, got it. I prefer to use the rune as a default container runtime in enclave-cc. Because of the unchanged's entry point and the same UX
> 
> The entry point change is not user visible or the `shim-rune` modification did not work?

yes shim-rune can make some workaroud to this. But it needs to spend sometime on this.

**Pull request closed without merging**
