### PR TITLE
enclave-agent: update image-rs dependency

### PR DESCRIPTION
**Pull request by wainersm**
In preparation for CoCo 0.5 release, bumped the image-rs for the commit xxx.

### CODE REVIEW

**Comment by wainersm** [comment]
Hi @mythi , could you please put the "do-not-merge" label on this PR? I am using my forked image-rs tree to check it won't break before I commit  https://github.com/confidential-containers/image-rs/pull/138

**Comment by dcmiddle** [comment]
> Hi @mythi , could you please put the "do-not-merge" label on this PR? I am using my forked image-rs tree to check it won't break before I commit [confidential-containers/image-rs#138](https://github.com/confidential-containers/image-rs/pull/138)

Can I just convert it to a `draft`?

**Comment by Xynnn007** [comment]
Hi @wainersm I think https://github.com/confidential-containers/enclave-cc/pull/140 can fix the error here

**Comment by wainersm** [comment]
Hi @Xynnn007 
> Hi @wainersm I think #140 can fix the error here

Yes, it fixed the error (thanks for promptly fixing it!). I will update this PR to re-run all tests.

Let me post the result of the clippy command as it container a warning you might want to handle in the future:
```
$ cargo clippy --manifest-path src/enclave-agent/Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
warning: the following packages contain code that will be rejected by a future version of Rust: lalrpop v0.19.8
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
```

**Comment by Xynnn007** [comment]
I think the new error 
```
   attestation_agent.a9f09f5a-cgu.6:(.text.callback+0x0): multiple definition of `callback'; /enclave-cc/src/enclave-agent/target/release/deps/libattestation_agent-0e461fc9defd58c3.rlib(attestation_agent-0e461fc9defd58c3.attestation_agent.4efd8566-cgu.6.rcgu.o):attestation_agent.4efd8566-cgu.6:(.text.callback+0x0): first defined here
          collect2: error: ld returned 1 exit status
```

is because https://github.com/confidential-containers/ocicrypt-rs/blob/main/Cargo.toml#L31 does not refer to the latest attestation-agent `c939d21`. Let me fix this inside ocicrypt-rs

**Comment by Xynnn007** [comment]
I made a fork and PR https://github.com/confidential-containers/ocicrypt-rs/pull/63 and that would help

**Comment by wainersm** [comment]
As https://github.com/confidential-containers/image-rs/pull/138 was merged, I updated this PR to use the upstream image-rs tree. It is ready to review.

**Review by Xynnn007 — APPROVED** [review]
LGTM, thanks!

**Review by mythi — APPROVED** [review]

**Pull request merged**
