### PR TITLE
build EAA/RATS-TLS

### PR DESCRIPTION
**Pull request by mythi**
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Comment by hairongchen** [comment]
my understanding, this PR is to build a verdictd container, and we can use this container for integration testing purpose only or it will be put into the payload image as well?

**Comment by mythi** [comment]
my idea was to use it for integration testing purposes only

**Comment by HaokunX-intel** [comment]
To enable signature feature, the `tag = "v0.2.0"` in the `image-rs` reference of  the `src/enclave-agent/Cargo.toml` need to be removed to use the latest crate.

**Comment by mythi** [comment]
depends on https://github.com/inclavare-containers/rats-tls/issues/109

**Comment by haosanzi** [comment]
> depends on [inclavare-containers/rats-tls#109](https://github.com/inclavare-containers/rats-tls/issues/109)

hi, mikko. Sorry for the late fix. This problem has been fixed in [pr](https://github.com/inclavare-containers/rats-tls/pull/129 ).  Thank you.

**Comment by mythi** [comment]
@HaokunX-intel @haosanzi I think this can be merged if it looks OK to you

**Review by dcmiddle — APPROVED** [review]

**Comment by HaokunX-intel** [comment]
LGTM

**Review by haosanzi — APPROVED** [review]

**Pull request merged**
